// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyA7h2KAszT8qCx_HK13csiufjLtm14CpUc',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:834971965063:web:abcdef',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '834971965063',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'video-calling-app-5c03b',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'video-calling-app-5c03b.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'video-calling-app-5c03b.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyA7h2KAszT8qCx_HK13csiufjLtm14CpUc',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:834971965063:android:698810271009f59572ca22',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '834971965063',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'video-calling-app-5c03b',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'video-calling-app-5c03b.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyAbpgtzkrwvv8PCqP5UQhJpAZYwmJWCb4o',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:834971965063:ios:0fea277f94c2a5bf72ca22',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '834971965063',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'video-calling-app-5c03b',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'video-calling-app-5c03b.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.videocall.videoCallApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyAbpgtzkrwvv8PCqP5UQhJpAZYwmJWCb4o',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:834971965063:ios:0fea277f94c2a5bf72ca22',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '834971965063',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'video-calling-app-5c03b',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'video-calling-app-5c03b.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.videocall.videoCallApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyA7h2KAszT8qCx_HK13csiufjLtm14CpUc',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:834971965063:web:abcdef',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '834971965063',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'video-calling-app-5c03b',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'video-calling-app-5c03b.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'video-calling-app-5c03b.firebasestorage.app',
  );
}